name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Create environment
        run: conda env create -f MLProject/conda.yaml

      - name: Activate environment and run MLflow
        run: |
          conda activate mlflow_env
          mlflow run MLProject
